<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Il2CppInterop.StructGenerator</RootNamespace>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClangSharp" Version="10.0.0-beta" />
    <PackageReference Include="CppAst" Version="0.8.0" />
    <PackageReference Include="libclang" Version="21.1.8" />
    <PackageReference Include="libclang.runtime.win-x64" Version="21.1.8" />
    <PackageReference Include="libClangSharp.runtime.win-x64" Version="21.1.8.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.2" />
    <PackageReference Include="PolySharp" Version="1.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
